### ISSUE TITLE
UI Retouch

### ISSUE THREAD

**Issue by fajarlazuarding** [febriinanda/enigma#19]
- change UI base color to red ( hex : #ad0000 ) - done
- all center - done
- preview is attached (ignore text 'cantumkan kode area') - done
- only home UI color will be changed to red - done
- logo will be provided later this noon - done

edit : 
- starred-teks modification to "angka tagihan di luar biaya administrasi sebesar Rp. 2.500,- dan denda keterlambatan pembayaran".
- photo attached.

![img_20170119_094522959](https://cloud.githubusercontent.com/assets/13043415/22091923/aa539f88-de2c-11e6-9f95-a2a96c4527fa.jpg)

fakyu

**Comment by fajarlazuarding** [comment]
edited.

**Comment by febriinanda** [comment]
lamo kau edit jar

**Comment by fajarlazuarding** [comment]
lah den edit taik kau

**Comment by febriinanda** [comment]
Yang iko wak close yo.
